### ISSUE TITLE
Update for the latest PostCSS version

### ISSUE THREAD

**Issue by dmitrykiselyov** [bit3725/postcss-shopify-settings-variables#4]
Hi Xingkui,

Thanks a lot for the plugin!
Please update the plugin for the latest version of PostCSS.

**Comment by bit3725** [comment]
@dmitrykiselyov 
Hi,
I just merged all pull requests and updated postcss dependency to 6.x. 
Hope it works for you now.

**Comment by dmitrykiselyov** [comment]
Hi @bit3725,

Yes, it works perfectly. Many thanks!
