### ISSUE TITLE
Any chance url() can support liquid filters?

### ISSUE THREAD

**Issue by cshold** [bit3725/postcss-shopify-settings-variables#7]
I'm trying to reduce the number of query strings placed on asset_urls generated by Shopify.

`url(logo.png)` ends up generating a link like:
`https://cdn.shopify.com/s/files/1/0027/7692/4218/t/2/assets/logo.png?1909108983063873987`

I was hoping to use it like this:
`url(logo.png | split: '?' | first)` so that I end up with:
`https://cdn.shopify.com/s/files/1/0027/7692/4218/t/2/assets/logo.png`

Alternatively some sort of way to use liquid directly without being converted to `{{ settings.variable_name }}`

**Comment by bit3725** [comment]
@cshold you can try version 0.3.1 to see if it solves your problem.

**Comment by cshold** [comment]
Amazing, works perfectly. Thanks!!
